# Generated by Django 4.2.1 on 2023-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapps', '0002_rename_write_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='playtime',
            field=models.IntegerField(default=0),
        ),
    ]
